/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Cliente.Principal;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciano Acosta
 */
public class pgestiones extends javax.swing.JPanel {

    /**
     * Creates new form pgestiones
     */
    public pgestiones() {
        initComponents();
    }

    public final void limpiar() {
        jtfNvaMarca.setText("");
        jtfCantidad.setText("");
        jtfDescripcion.setText("");
        jtfMarca.setText("");
        jtfNombre.setText("");
        jtfNuvoColor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlColor = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlStock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNvaMarca = new javax.swing.JTextField();
        jtfNuvoColor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        btnBuscarP = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        cbTalle = new javax.swing.JComboBox<>();
        cbColor = new javax.swing.JComboBox<>();
        jtfCantidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtColor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCaracteristicas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtMarca = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cbTarea = new javax.swing.JComboBox<>();
        btnAgregarMarca = new javax.swing.JButton();
        btnAgregarColor = new javax.swing.JButton();
        btnAgregarCantidad = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jlLimite = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(12, 72, 56));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestionar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jlColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlColor.setForeground(new java.awt.Color(12, 72, 56));
        jlColor.setText("COLOR");

        jlMarca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlMarca.setForeground(new java.awt.Color(12, 72, 56));
        jlMarca.setText("MARCAS");

        jlStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlStock.setForeground(new java.awt.Color(12, 72, 56));
        jlStock.setText("STOCK");

        jLabel2.setText("Nueva Marca");

        jtfNuvoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNuvoColorActionPerformed(evt);
            }
        });

        jLabel3.setText("Nuevo Color");

        Nombre.setText("Codigo");

        btnBuscarP.setBackground(new java.awt.Color(31, 192, 132));
        btnBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo De talle" }));
        cbTipo.setSelectedIndex(-1);
        cbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoItemStateChanged(evt);
            }
        });
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        cbTalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar talle" }));
        cbTalle.setSelectedIndex(-1);
        cbTalle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTalleItemStateChanged(evt);
            }
        });

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Color" }));
        cbColor.setSelectedIndex(-1);

        jLabel15.setText("Tipo de talle");

        jLabel8.setText("Talle");

        jLabel9.setText("Color");

        jLabel16.setText("Cantidad");

        jLabel4.setText("Descripción");

        jLabel6.setText("Marca");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("NUEVAS CARACTERISTICAS");

        jtColor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtColor);
        if (jtColor.getColumnModel().getColumnCount() > 0) {
            jtColor.getColumnModel().getColumn(0).setResizable(false);
            jtColor.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        jtCaracteristicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talle", "Color", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtCaracteristicas);
        if (jtCaracteristicas.getColumnModel().getColumnCount() > 0) {
            jtCaracteristicas.getColumnModel().getColumn(0).setResizable(false);
            jtCaracteristicas.getColumnModel().getColumn(0).setPreferredWidth(25);
            jtCaracteristicas.getColumnModel().getColumn(1).setResizable(false);
            jtCaracteristicas.getColumnModel().getColumn(1).setPreferredWidth(25);
            jtCaracteristicas.getColumnModel().getColumn(2).setResizable(false);
            jtCaracteristicas.getColumnModel().getColumn(2).setPreferredWidth(25);
        }

        jtMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtMarca);
        if (jtMarca.getColumnModel().getColumnCount() > 0) {
            jtMarca.getColumnModel().getColumn(0).setResizable(false);
            jtMarca.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("TAREA");

        cbTarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca", "Color", "Stock" }));

        btnAgregarMarca.setBackground(new java.awt.Color(31, 192, 132));
        btnAgregarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/garrapata (1).png"))); // NOI18N
        btnAgregarMarca.setText("Agregar Marca");
        btnAgregarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMarcaActionPerformed(evt);
            }
        });

        btnAgregarColor.setBackground(new java.awt.Color(31, 192, 132));
        btnAgregarColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/garrapata (1).png"))); // NOI18N
        btnAgregarColor.setText("Agregar Color");
        btnAgregarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColorActionPerformed(evt);
            }
        });

        btnAgregarCantidad.setBackground(new java.awt.Color(31, 192, 132));
        btnAgregarCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/garrapata (1).png"))); // NOI18N
        btnAgregarCantidad.setText("Agregar");
        btnAgregarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCantidadActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Stock: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(cbTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(Nombre)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel8)
                                                        .addGap(16, 16, 16)
                                                        .addComponent(cbTalle, 0, 1, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnAgregarCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(jLabel5)))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnBuscarP)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlLimite)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlStock))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnAgregarMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jtfNvaMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                                .addGap(109, 109, 109))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnAgregarColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jtfNuvoColor, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)
                                                .addComponent(jlColor))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlMarca)))))
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMarca)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jtfNvaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlColor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jtfNuvoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarColor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlStock)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jlLimite))
                            .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nombre)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cbTalle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNuvoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNuvoColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNuvoColorActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        Principal p = new Principal();

        if (jtfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Indique el producto a gestionar");
        } else {
            try {
                if (p.existe(jtfNombre.getText())) {
                    agregarCaracteristicas(jtfNombre.getText());
                    listarCaracteristicas(jtfNombre.getText());
                } else {
                    showMessageDialog(null, "El producto no exite \n Agregue producto en la seccion agregar producto");
                    jtfNombre.setText("");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void cbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoItemStateChanged
        Principal p = new Principal();
        cbTalle.removeAllItems();
        if (cbTipo.getSelectedIndex() > -1) {
            try {
                ArrayList<String> talle = p.llenarCombos(cbTipo.getSelectedItem().toString());
                for (int i = 0; i < talle.size(); i++) {
                    cbTalle.addItem(talle.get(i));
                }
            } catch (RemoteException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbTipoItemStateChanged

    private void btnAgregarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMarcaActionPerformed
        if (jtfNvaMarca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Indique la marca a incluir");

        } else {
            try {
                Principal p = new Principal();
                p.agregarMarca(jtfNvaMarca.getText());
                listarTablaMarca();
            } catch (RemoteException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAgregarMarcaActionPerformed

    private void btnAgregarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColorActionPerformed
        if (jtfNuvoColor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Indique el color a incluir");
        } else {
            try {
                Principal p = new Principal();
                p.agregarColor(jtfNuvoColor.getText());
                listarTablaColor();
            } catch (RemoteException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAgregarColorActionPerformed

    private void btnAgregarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCantidadActionPerformed
        Principal p = new Principal();
        if (jtfCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Indique la cantidad a incluir");
        } else {
            try {
                p.actualizarStock(jtfNombre.getText(), jtfCantidad.getText(), cbTalle.getSelectedItem().toString(), cbColor.getSelectedItem().toString());
                agregarCaracteristicas(jtfNombre.getText());
                listarCaracteristicas(jtfNombre.getText());
            } catch (RemoteException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAgregarCantidadActionPerformed

    private void cbTalleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTalleItemStateChanged

    }//GEN-LAST:event_cbTalleItemStateChanged

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    public javax.swing.JButton btnAgregarCantidad;
    public javax.swing.JButton btnAgregarColor;
    public javax.swing.JButton btnAgregarMarca;
    public javax.swing.JButton btnBuscarP;
    public javax.swing.JComboBox<String> cbColor;
    public javax.swing.JComboBox<String> cbTalle;
    public javax.swing.JComboBox<String> cbTarea;
    public javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel jlColor;
    public javax.swing.JLabel jlLimite;
    public javax.swing.JLabel jlMarca;
    public javax.swing.JLabel jlStock;
    public javax.swing.JTable jtCaracteristicas;
    public javax.swing.JTable jtColor;
    public javax.swing.JTable jtMarca;
    public javax.swing.JTextField jtfCantidad;
    public javax.swing.JTextField jtfDescripcion;
    public javax.swing.JTextField jtfMarca;
    public javax.swing.JTextField jtfNombre;
    public javax.swing.JTextField jtfNuvoColor;
    public javax.swing.JTextField jtfNvaMarca;
    // End of variables declaration//GEN-END:variables

    void cargarCombos() throws NotBoundException {
        try {
            Principal p = new Principal();
            cbTalle.removeAllItems();
            cbColor.removeAllItems();
            cbTipo.removeAllItems();
            
            ArrayList<ArrayList<String>> combos = p.cargarCombosStock();
            
            for (int i = 0; i < combos.get(0).size(); i++) {
                cbTipo.addItem(combos.get(0).get(i));
            }
            for (int i = 0; i < combos.get(1).size(); i++) {
                cbColor.addItem(combos.get(1).get(i));
            }
        } catch (RemoteException ex) {
            Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void listarTablaColor() throws NotBoundException {
        try {
            Principal p = new Principal();
            String[][] colores = p.listarTablaColor();
            
            DefaultTableModel datosColor = (DefaultTableModel) jtColor.getModel();
            datosColor.setNumRows(0);
            
            for (int i = 0; i < colores.length; i++) {
                Object[] fila = {colores[i][0]
                };
                
                datosColor.addRow(fila);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void listarTablaMarca() throws NotBoundException {
        try {
            Principal p = new Principal();
            String[][] marcas = p.listarTablaMarca();
            
            DefaultTableModel datosMarca = (DefaultTableModel) jtMarca.getModel();
            datosMarca.setNumRows(0);
            
            for (int i = 0; i < marcas.length; i++) {
                Object[] fila = {marcas[i][0]
                };
                
                datosMarca.addRow(fila);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void agregarCaracteristicas(String text) throws NotBoundException {
        try {
            Principal p = new Principal();
            
            ArrayList<String> producto = p.agregarCaracteristicas(jtfNombre.getText());
            
            jtfDescripcion.setText(producto.get(1));
            jtfMarca.setText(producto.get(2));
            jtfDescripcion.setEnabled(false);
            jtfMarca.setEnabled(false);
            jlLimite.setText(producto.get(7));
        } catch (RemoteException ex) {
            Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void listarCaracteristicas(String text) throws NotBoundException {
        try {
            Principal p = new Principal();
            DefaultTableModel datosProductos = (DefaultTableModel) jtCaracteristicas.getModel();
            datosProductos.setNumRows(0);
            
            String[][] listaCarac = p.listarCaracteristicas(text);
            
            for(int i = 0;i<listaCarac.length;i++){
                Object[] fila = {listaCarac[i][0],
                    listaCarac[i][1],
                    listaCarac[i][2]};
                
                datosProductos.addRow(fila);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(pgestiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
